---
# tasks file for ec2-instance


- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
   name: "{{instance_name}}"
   key_name: "{{key_name}}"
   vpc_subnet_id: "{{vpc_subnet_id}}"
   instance_type: "{{instance_type}}"
   security_group: default
   region: ap-south-1
   aws_access_key: "{{ec2_access_key}}"
   aws_secret_key: "{{ec2_secret_key}}"
   network_interfaces:
     - assign_public_ip: true
   image_id: "{{image_id}}"
  

